remote_theme: "mmistakes/minimal-mistakes@4.13.0"

minimal_mistakes_skin: "default"

# Site Settings
locale: "en"
title: "Leon Palafox"
title_separator: "-"
name: &name Leon Palafox
description: "Personal website."
url: "https://leonpalafox.github.io"
baseurl: "" # the subpath of your site, e.g. "/blog"
repository: "leonpalafox/leonpalafox.github.io"
teaser:
# breadcrumbs: false
words_per_minute: 200

comments:
  provider:
  disqus:
    shortname:
  discourse:
    server:
  facebook:
    appid:
    num_posts:
    colorscheme:

staticman:
  allowedFields:
  branch:
  commitMessage:
  filename:
  format:
  moderation:
  path:
  requiredFields:
  transforms:
    email:
  generatedFields:
    date:
      type:
      options:
        format:

reCaptcha:
  siteKey:
  secret:

atom_feed:
  path:

# SEO Related
google_site_verification:
bing_site_verification:
yandex_site_verification:
naver_site_verification:

# Social Sharing
twitter:
  username:
facebook:
  username:
  app_id:
  publisher:
og_image:

social:
  type:
  name:
  links:

# --- Analytics (choose ONE method) ---
# Simple GA4 (recommended):
google_analytics: G-M9BV46V3PD

# Remove this whole block to avoid conflicts:
# analytics:
#   provider: false
#   google:
#     tracking_id:

# Site Author
author:
  name: *name
  avatar: "/assets/images/bio-photo.png"
  bio: "I'm Machine Learning Director at Banorte Financial Group. I got my PhD at the University of Tokyo and am a Lecturer on AI at Universidad Panamericana."
  location: "Mexico City, MEXICO"
  email: lpalafox@up.edu.mx
  uri:
  bitbucket:
  codepen:
  dribbble:
  flickr:
  facebook:
  foursquare:
  github: "leonpalafox"
  gitlab:
  google_plus:
  keybase:
  instagram:
  lastfm:
  linkedin: "leonpalafox"
  pinterest:
  soundcloud:
  stackoverflow: "486262/leon-palafox"
  steam:
  tumblr:
  twitter: "leonpalafox"
  vine:
  weibo:
  xing:
  youtube:

# Reading Files
include:
  - .htaccess
  - _pages
  - _events
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"*
